name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git
          branches: |
            ['main']
        env:
          GITHUB_TOKEN: "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"
      - name: Echo version number
        run: |
          VERSION=$(npx semantic-release --dry-run | grep -oP '(?<=nextRelease: ).*')
          echo "The version number is $VERSION"
     
